def get_area(bbox):
    return (bbox[2] - bbox[0]) * (bbox[3] - bbox[1])


def is_car(item):
    return item.get('class') in ['bus', 'car', 'motorcycle', 'scooter', 'shuttle_taxi', 'truck']

translator = {
    'bicycle': 'велосипед',
    'bus': 'автобус',
    'car': 'автомобиль',
    'motorcycle': 'мотоцикл',
    'pedestrian': 'пешеход',
    'scooter': 'скутер',
    'shuttle_taxi': 'маршрутка',
    'truck': 'грузовик',
    '100Limit': 'ограничение скорости 100',
    '10Limit': 'ограничение скорости 10',
    'OneWayRoad': 'одностороннее движение',
    'OneWayRoadRight': 'одностороннее движение направо',
    '20Limit': 'ограничение скорости 20',
    '30Limit': 'ограничение скорости 30',
    '40Limit': 'ограничение скорости 40',
    '50Limit': 'ограничение скорости 50',
    '5Limit': 'ограничение скорости 5',
    '60Limit': 'ограничение скорости 60',
    '70Limit': 'ограничение скорости 70',
    '80Limit': 'ограничение скорости 80',
    'BusRoad': 'маршрутная полоса',
    'BusStop': 'остановка',
    'Children': 'осторожно дети',
    'Forbidden': 'движение запрещено',
    'ForwardAndLeftWay': 'по полосе прямо и налево',
    'ForwardAndRightWay': 'по полосе прям и направо',
    'ForwardWay': 'по полосе только прямо',
    'Information': 'информация',
    'LeftAndRightWay': 'по полосе налево или направо',
    'LeftWay': 'по полосе налево',
    'NoPark': 'остановка запрещена',
    'NoParkAndStop': 'остановка и стоянка запрещена',
    'NoRight': 'запрещен поворот направо',
    'Parking': 'парковка',
    'Crossroad': 'пешеходный переход',
    'RightWay': 'поворот направо',
    'RingRoad': 'кольцевое движение',
    'Special': 'информационный знак',
    'Stop': 'знак стоп',
    'Tram': 'трамваи',
    'DeadEnd': 'тупик',
    'GiveWay': 'уступи дорогу',
    'Warning': 'предупреждение',
    'OneWayRoadEnd': 'конец одностороннего движения',
    'MainRoadEnd': 'конец главной дороги',
    'MainRoad': 'главная дорога',
    'NoLeft': 'запрещен поворот налево',
    'ProhibitorySign': 'движение запрещено',
    'PassLeft': 'объезд слева',
    'PassLeftRight': 'объезд справа или слева',
    'PassRight': 'объезд справа',
    'OnlyForward': 'движение только прямо',
    'OnlyForwardAndLeft': 'движение только прямо и налево',
    'OnlyForwardAndRight': 'движение только прямо и направо',
    'OnlyLeft': 'движение только налево',
    'OnlyRight': 'движение только направо',
    'OnlyRightLeft': 'движение только направо или налево'
}
